apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql  # Sửa lại selector cho phù hợp với deployment
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306